[profile.default]
contracts        = 'contracts'    # The contract directory
test             = 'tests'        # The test directory
libs             = ['modules']    # A list of library directories
optimizer        = false          # Enable or disable the solc optimizer
auto_detect_solc = true           # Automatically detect the solc version
verbosity        = 3              # The verbosity of tests
block_timestamp  = 1_622_400_000  # Timestamp for tests (non-zero)
evm_version      = 'shanghai'     # EVM version to use
fs_permissions   = [{ access = "read", path = "./"}]

[profile.default.fuzz]
runs = 1_000  # Number of fuzz runs

[profile.ci.fuzz]
runs = 100_000

[profile.production]
optimizer      = true  # Enable or disable the solc optimizer
optimizer_runs = 200   # The number of optimizer runs
